# Generated by Django 2.2.7 on 2020-02-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default='e', max_length=20),
            preserve_default=False,
        ),
    ]
