# Generated by Django 2.2.7 on 2020-02-29 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_refund_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='e', upload_to='image'),
            preserve_default=False,
        ),
    ]
