# Generated by Django 2.2.7 on 2020-04-05 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_auto_20200328_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='save_info',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
