# Generated by Django 2.2.7 on 2020-04-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_auto_20200418_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='mobile',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
