# Generated by Django 2.2.7 on 2020-04-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_auto_20200419_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='zip',
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
    ]
