# Generated by Django 2.2.7 on 2020-04-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_auto_20200419_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='ordered',
            field=models.BooleanField(),
        ),
    ]
