# Generated by Django 2.2.7 on 2020-04-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_auto_20200420_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='being_delivered',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='received',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='refund_granted',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='refund_requested',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='refund',
            name='accepted',
            field=models.BooleanField(),
        ),
    ]
