# Generated by Django 3.0.5 on 2020-04-21 16:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_auto_20200420_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=cloudinary.models.CloudinaryField(default='1', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
